config/routes.rb
Rails.application.routes.draw do

root 'users#index'

resources :users
resources :courses

get "signin" => "sessions#new", as: :signin
post "signin" => "sessions#create"
get "signout" => "sessions#destroy", as: :signout
get "signup" => "registrations#new", as: :signup
post "signup" => "registrations#create"

end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :user_name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def index
end

private
  def current_user
    @current_user ||=User.find_by(id: session[:user_id])
  end

  def authenticate
    if not current_user
    redirect_to signin_path
    end
  end

helper_method :current_user


end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

before_action :authenticate

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def edit
    @course = Course.find(params[:id])
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path
    else
      render :new
    end
  end

  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
      redirect_to courses_path
    else
      render :edit
    end
  end



  def show
    @course = Course.find(params[:id])
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_path
  end

private

def course_params
  params.require(:course).permit(:title, :day_night)
end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path
      else
        render :new
      end
    end

  private
    def user_params
      params.require(:user).permit(:user_name, :password, :about)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController  

  def create
    @user = User.find_by_user_name(params[:user_name])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      @sign_in_error = 'Invalid email/password'
      render :new
    end
  end


  def destroy
    session.destroy
    redirect_to signin_path
  end


end

app/controllers/users_controller.rb
class UsersController <ApplicationController

before_action :authenticate

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @user = User.find (params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

private
def user_params
  params.require(:user).permit(:user_name, :password, :about)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :day_night, 'Day or Night'%>
<%= f.select :day_night, [['Day'], ['Night']]%>

<%= f.submit %>

<% end %>

app/views/courses/edit.html.erb
<h1> Edit the Course! </h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<br>
<%= link_to 'Add Course', new_course_path %>
<h1> Welcome to the list of Courses! </h1>
<table  border="1">
  <tr>
    <th> Title </th>
    <th> Day or Night </th>
    <th> Update or Remove Course </th>
  </tr>

  <tbody>
    <% @courses.each do |course| %>
    <tr>
    <td> <%= link_to course.title, course_path(course) %></td>
    <% if course.day_night == true %>
    <td>Day</td>
    <% else %>
    <td>Night</td>
    <% end %>
    <td> <%= link_to "Update Course", edit_course_path(course) %>
      <%= link_to "Delete Course", course_path(course), method: :delete %>
      </td>
  </tr>
  </tbody>
  <% end %>
</table>

app/views/courses/new.html.erb
<h1> Add A New Course! </h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<h1>Title: <%= @course.title %></h1>
<br>
<%= "Day or Night:" %>
<% if @course.day_night == true %>
<%= "Day" %>
<% else %>
<%= "Night" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>HayleyBlackstockWeek7</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <% if current_user%>
    <%= link_to current_user.user_name %> |
    <%= link_to "signout", signout_path %>
  <% else %>
    <%= link_to "signup", signup_path %>
    <%= link_to "signin", signin_path %>
<% end %>

<%= yield %>

  </body>
  </html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<%= f.label :user_name %>
<%= f.text_field :user_name %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :about %>
<%= f.text_field :about %>

<%= f.submit 'Save' %>
<% end %>

app/views/users/edit.html.erb
<h1> Editing Student </h1>

<%= render 'form' %>

app/views/users/index.html.erb
<br>
<%= link_to 'Course List', courses_path %>
<h1> Students </h1>
<%= link_to 'Create Student', new_user_path %>
<table border="1">

  <thead>
    <tr>
      <th> User Name </th>
      <th> About </th>
      <th> Update or Delete </th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.user_name, user %></td>
      <td><%= user.about %></td>
      <td><%= link_to 'Edit Student', edit_user_path(user) %>
        <%= link_to 'Destroy Student', user, method: :delete %>
      </td>
    </tr>
    <% end %>
</tbody>
</table>

app/views/users/new.html.erb
<h1> Create a Student </h1>

<%= render 'form' %>

<!-- <%= form_for @user do |f| %>
<%= f.submit 'Create New Student' %>
<% end %> -->

app/views/users/show.html.erb
<br>
<%= "User Name: " %><%= @user.user_name %>
<br>
<%= "About: " %><%= @user.about %>